name = "learnability"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LTS", "ConditionalSimulation", "Convergence", "Learnability", "CoinductiveBisimulation", "LearnabilityConvergence", "SymbolicISA", "Branch", "Bisimulation", "Quotient", "BranchExample", "MachineISA", "BranchConvergence", "Composition", "ProgramStructure", "EffectiveObservability", "CircularCoinduction", "ModelEq", "Instances"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "LTS"

[[lean_lib]]
name = "Core"

[[lean_lib]]
name = "ConditionalSimulation"

[[lean_lib]]
name = "Convergence"

[[lean_lib]]
name = "Learnability"

[[lean_lib]]
name = "SymExec"

[[lean_lib]]
name = "CoinductiveBisimulation"

[[lean_lib]]
name = "LearnabilityConvergence"

[[lean_lib]]
name = "SymbolicISA"

[[lean_lib]]
name = "Branch"

[[lean_lib]]
name = "BranchConvergence"

[[lean_lib]]
name = "Bisimulation"

[[lean_lib]]
name = "Quotient"

[[lean_lib]]
name = "BranchExample"

[[lean_lib]]
name = "MachineISA"

[[lean_lib]]
name = "Instances"

[[lean_lib]]
name = "Composition"

[[lean_lib]]
name = "ProgramStructure"

[[lean_lib]]
name = "EffectiveObservability"

[[lean_lib]]
name = "CircularCoinduction"

[[lean_lib]]
name = "ModelEq"
